export const styles: Record<string, React.CSSProperties> = {
  root: {
    minHeight: "100vh",
    background:
      "linear-gradient(135deg, #050914 0%, #0a1628 40%, #080d1e 100%)",
    fontFamily: '"DM Sans", "Segoe UI", system-ui, sans-serif',
    color: "#e2e8f0",
  },
  topbar: {
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    background: "rgba(5,9,20,0.85)",
    backdropFilter: "blur(20px)",
    position: "sticky" as const,
    top: 0,
    zIndex: 50,
  },
  topbarInner: {
    maxWidth: 1280,
    margin: "0 auto",
    padding: "14px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "#94a3b8",
    textDecoration: "none",
    fontWeight: 500,
    transition: "color 0.2s",
  },
  storeBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 12px",
    borderRadius: 20,
    background: "rgba(99,102,241,0.15)",
    border: "1px solid rgba(99,102,241,0.3)",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase" as const,
    color: "#a5b4fc",
  },
  container: {
    maxWidth: 1280,
    margin: "0 auto",
    padding: "32px 24px",
  },
  hero: {
    marginBottom: 40,
    padding: "48px 56px",
    borderRadius: 24,
    border: "1px solid rgba(255,255,255,0.07)",
    backdropFilter: "blur(8px)",
    position: "relative" as const,
    overflow: "hidden",
  },
  heroGlow: {
    position: "absolute" as const,
    top: -80,
    right: -80,
    width: 300,
    height: 300,
    borderRadius: "50%",
    pointerEvents: "none" as const,
  },
  heroTitle: {
    fontSize: 36,
    fontWeight: 700,
    color: "#f8fafc",
    margin: 0,
    letterSpacing: "-0.02em",
    lineHeight: 1.2,
  },
  heroSub: {
    marginTop: 12,
    fontSize: 15,
    color: "#94a3b8",
    lineHeight: 1.65,
    maxWidth: 600,
  },
  howItWorks: {
    marginTop: 28,
    padding: "18px 22px",
    borderRadius: 16,
    background: "rgba(16,185,129,0.07)",
    border: "1px solid rgba(16,185,129,0.18)",
    display: "flex",
    gap: 14,
    alignItems: "flex-start",
    maxWidth: 580,
  },
  howItWorksText: {
    fontSize: 13.5,
    color: "#a7f3d0",
    lineHeight: 1.6,
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "1fr 380px",
    gap: 28,
    alignItems: "start",
  },
  /* Catalog */
  catalogHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    gap: 16,
    flexWrap: "wrap" as const,
  },
  searchWrap: {
    position: "relative" as const,
    flex: 1,
    maxWidth: 380,
  },
  searchInput: {
    width: "100%",
    height: 44,
    padding: "0 16px 0 44px",
    borderRadius: 12,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(255,255,255,0.05)",
    color: "#f1f5f9",
    fontSize: 14,
    outline: "none",
    transition: "border-color 0.2s, background 0.2s",
    boxSizing: "border-box" as const,
  },
  searchIcon: {
    position: "absolute" as const,
    left: 14,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#64748b",
    pointerEvents: "none" as const,
  },
  filterLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "#94a3b8",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  checkbox: {
    width: 16,
    height: 16,
    accentColor: "#6366f1",
  },
  productsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: 20,
  },
  productCard: {
    borderRadius: 20,
    overflow: "hidden",
    background: "rgba(15,23,42,0.7)",
    border: "1px solid rgba(255,255,255,0.07)",
    backdropFilter: "blur(8px)",
    transition: "transform 0.2s, border-color 0.2s, box-shadow 0.2s",
    display: "flex",
    flexDirection: "column" as const,
  },
  productImage: {
    height: 220,
    overflow: "hidden",
    background: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
    position: "relative" as const,
  },
  productImageImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover" as const,
    display: "block",
  },
  productBody: {
    padding: "20px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
    flex: 1,
  },
  productContent: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
  },
  productActions: {
    marginTop: "auto",
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
  },
  badgeRow: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap" as const,
  },
  badge: (color: string) => ({
    padding: "3px 10px",
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.04em",
    background:
      color === "slate"
        ? "rgba(100,116,139,0.2)"
        : color === "indigo"
          ? "rgba(99,102,241,0.15)"
          : color === "rose"
            ? "rgba(239,68,68,0.15)"
            : "rgba(100,116,139,0.2)",
    color:
      color === "slate"
        ? "#94a3b8"
        : color === "indigo"
          ? "#a5b4fc"
          : color === "rose"
            ? "#fca5a5"
            : "#94a3b8",
    border: `1px solid ${
      color === "slate"
        ? "rgba(100,116,139,0.2)"
        : color === "indigo"
          ? "rgba(99,102,241,0.25)"
          : color === "rose"
            ? "rgba(239,68,68,0.25)"
            : "rgba(100,116,139,0.2)"
    }`,
  }),
  productName: {
    fontSize: 17,
    fontWeight: 700,
    color: "#f8fafc",
    margin: 0,
    letterSpacing: "-0.01em",
  },
  productPrice: {
    fontSize: 20,
    fontWeight: 700,
    color: "#6366f1",
    margin: "2px 0 0",
    letterSpacing: "-0.02em",
  },
  productDesc: {
    fontSize: 13.5,
    color: "#64748b",
    lineHeight: 1.6,
    margin: 0,
  },
  variantLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "#94a3b8",
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    display: "block",
    marginBottom: 6,
  },
  variantSelect: {
    width: "100%",
    height: 42,
    padding: "0 12px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(15,23,42,0.8)",
    color: "#f1f5f9",
    fontSize: 13.5,
    outline: "none",
  },
  inventoryRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    borderRadius: 10,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.06)",
  },
  inventoryLabel: {
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.1em",
    color: "#475569",
  },
  inventoryValue: {
    fontSize: 13,
    fontWeight: 600,
    color: "#94a3b8",
    marginTop: 2,
  },
  qtyControls: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  qtyBtn: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(255,255,255,0.05)",
    color: "#94a3b8",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "background 0.15s, border-color 0.15s",
  },
  qtyValue: {
    minWidth: 28,
    textAlign: "center" as const,
    fontSize: 14,
    fontWeight: 700,
    color: "#f8fafc",
  },
  addToCartBtn: {
    width: "100%",
    height: 44,
    borderRadius: 12,
    border: "none",
    background: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)",
    color: "#fff",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    transition: "opacity 0.2s, transform 0.1s",
    letterSpacing: "0.01em",
  },
  addToCartBtnDisabled: {
    opacity: 0.4,
    cursor: "not-allowed",
    transform: "none",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "72px 24px",
    borderRadius: 20,
    border: "1px dashed rgba(255,255,255,0.1)",
    background: "rgba(255,255,255,0.02)",
    textAlign: "center" as const,
  },
  emptyTitle: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: 700,
    color: "#f1f5f9",
  },
  emptyDesc: {
    marginTop: 6,
    fontSize: 13.5,
    color: "#475569",
    maxWidth: 340,
  },
  loadingState: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "72px 24px",
    gap: 10,
    fontSize: 14,
    color: "#475569",
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,0.05)",
    background: "rgba(255,255,255,0.02)",
  },
  /* Sidebar */
  sidebar: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 20,
    position: "sticky" as const,
    top: 76,
  },
  panel: {
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,0.07)",
    background: "rgba(15,23,42,0.75)",
    backdropFilter: "blur(12px)",
    padding: 24,
  },
  panelTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "#f8fafc",
    margin: 0,
    letterSpacing: "-0.01em",
  },
  panelSub: {
    fontSize: 13,
    color: "#475569",
    marginTop: 4,
  },
  cartEmpty: {
    marginTop: 16,
    padding: "20px 16px",
    borderRadius: 12,
    border: "1px dashed rgba(255,255,255,0.08)",
    fontSize: 13,
    color: "#475569",
    textAlign: "center" as const,
    lineHeight: 1.6,
  },
  cartItem: {
    padding: "14px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.06)",
    marginTop: 10,
  },
  cartItemHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  cartItemName: {
    fontSize: 13.5,
    fontWeight: 600,
    color: "#f1f5f9",
    margin: 0,
  },
  cartItemVariant: {
    fontSize: 12,
    color: "#475569",
    marginTop: 2,
  },
  cartRemoveBtn: {
    background: "none",
    border: "none",
    color: "#ef4444",
    cursor: "pointer",
    padding: "2px",
    display: "flex",
    alignItems: "center",
    opacity: 0.7,
    transition: "opacity 0.15s",
    flexShrink: 0,
  },
  cartItemFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
  },
  cartItemPrice: {
    fontSize: 14,
    fontWeight: 700,
    color: "#a5b4fc",
  },
  divider: {
    height: 1,
    background: "rgba(255,255,255,0.06)",
    margin: "16px 0",
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: 13,
    color: "#64748b",
    marginBottom: 8,
  },
  summaryTotal: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 12,
    borderTop: "1px solid rgba(255,255,255,0.08)",
    marginTop: 4,
  },
  summaryTotalLabel: {
    fontSize: 15,
    fontWeight: 700,
    color: "#f8fafc",
  },
  summaryTotalValue: {
    fontSize: 18,
    fontWeight: 700,
    color: "#6366f1",
  },
  /* Form */
  formGroup: {
    marginTop: 16,
    display: "flex",
    flexDirection: "column" as const,
    gap: 12,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "#94a3b8",
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    display: "block",
    marginBottom: 6,
  },
  fieldInput: {
    width: "100%",
    height: 42,
    padding: "0 14px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(255,255,255,0.04)",
    color: "#f1f5f9",
    fontSize: 13.5,
    outline: "none",
    transition: "border-color 0.2s",
    boxSizing: "border-box" as const,
  },
  fieldTextarea: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(255,255,255,0.04)",
    color: "#f1f5f9",
    fontSize: 13.5,
    outline: "none",
    resize: "vertical" as const,
    minHeight: 80,
    boxSizing: "border-box" as const,
    transition: "border-color 0.2s",
    fontFamily: "inherit",
  },
  twoCol: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  checkoutBtn: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    border: "none",
    background: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)",
    color: "#fff",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    transition: "opacity 0.2s",
    letterSpacing: "0.01em",
    marginTop: 4,
  },
  orderStatusPanel: (tone: ReturnType<typeof statusTone>) => ({
    borderRadius: 20,
    border: `1px solid ${tone.border}`,
    background: tone.bg,
    padding: "20px 24px",
    marginBottom: 28,
  }),
  orderStatusLabel: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase" as const,
    letterSpacing: "0.14em",
    color: "#94a3b8",
  },
  orderStatusTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "#f8fafc",
    margin: "4px 0 6px",
  },
  orderStatusMsg: {
    fontSize: 13.5,
    color: "#94a3b8",
    lineHeight: 1.55,
  },
  orderBadgesRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap" as const,
    marginTop: 14,
  },
};
